---
name: "\U0001F41B Bug or Problem Report"
about: Bug or problems faced with the Model Comparison Tool
title: ''
labels: ''
assignees: ''

---

Short Information 
* Used Case:
* Used Tool version: `0.0.0` | `0.0.1` | `...`

### Problem Definition Briefly (might be explained in steps)
* 

### Expected Output
*

### Actual Output
*

### Extra information (can contain screen shots)