name: 🚀 Feature Request
description: Suggest a Model Comparison idea

labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Model Comparison Tool 🚀 Feature Request! 

  - type: textarea
    attributes:
      label: Short Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in Model Comparison Tool exactly?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Use case
      description: |
        Describe the use case of your feature request shortly. It will help us to understand and prioritize the feature request.
      placeholder: |
        How would this feature be used?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to say?